version: '3.1'

services: 
  mongo:
    image: mongo:4.1.13
    restart: unless-stopped
    ports: 
      - 27017:27017
    volumes: 
      - mongo-data:/etc/mongo

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081

  app:
    build: .
    restart: unless-stopped
    command: run
    environment:
        MONGODB_HOST: mongo
        WAIT_HOSTS: mongo:27017
    ports:
      - 80:5000
    depends_on:
      - mongo

volumes:
  mongo-data:
