version: '3.1'

services: 
  mongo:
    image: mongo:4.1.13
    restart: unless-stopped
    ports: 
      - 27017:27017
    volumes: 
      - mongo-data:/etc/mongo

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081

volumes:
  mongo-data:
