version: 2.1

jobs:
  check:
    docker:
      - image: circleci/python:3.7.3-stretch
      - image: circleci/mongo:4.2-bionic-ram

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}

      - run:
          name: Install tox
          command: |
            python3 -m venv venv	
            source venv/bin/activate
            pip install tox

      - run:
          name: Run linters
          command: |
            . venv/bin/activate
            tox -e flake8,mypy

      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:27017 -timeout 1m

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - ".tox"

workflows:
  check-code:
    jobs:
      - check
